---
driver:
  name: dokken
  chef_version: latest
  privileged: true
  volumes: [ '/var/lib/docker' ]

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      image: centos:7
      intermediate_instructions:
        - RUN yum install iptables -y
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: default
    excludes:
      - hello
    run_list:
      - recipe[dokken_test::default]
    attributes:
      dokken_test:
        revision: <%= `git rev-parse HEAD` %>
